--- 
  - name: Demo on looping
    hosts: localhost
    connection: local
    tasks:
        - name: Printing fruits
          ansible.builtin.debug:
            msg: The fruits are {{item}}
          loop: 
            - apple
            - bananna
            - orange
