--- 
  - name: Demo on looping
    hosts: localhost
    connection: local
    vars:
      items_to_loop:
        - item1
        - item2
        - item3
    tasks:
      - name: Printing fruits
        ansible.builtin.debug:
          msg:  "The fruits are {{ item }}"
        loop : "{{ items_to_loop }}"

  