# --- 
#   - name: Demo on looping
#     hosts: localhost
#     connection: local
#     vars:
#       items_to_loop:
#         - apple
#         - bananna
#         - orange
#     tasks:
#       - name: Printing fruits
#         ansible.builtin.debug:
#           msg:  "The fruits are {{ item }}"
#         loop : "{{ items_to_loop }}"


--- 
  - name: Demo on loop
    hosts: localhost
    connection: local
    vars:
      items_to_loop:
        - bus
        - car
        - bike
        - auto
    tasks:
      - name: printing vehicals
        ansible.builtin.debug:
          msg: "the vehicle is {{ item }}"
        loop: "{{ items_to_loop }}"

  