# --- 
#   - name: Demo on looping
#     hosts: localhost
#     connection: local
#     vars:
#       items_to_loop:
#         - apple
#         - bananna
#         - orange
#     tasks:
#       - name: Printing fruits
#         ansible.builtin.debug:
#           msg:  "The fruits are {{ item }}"
#         loop : "{{ items_to_loop }}"


--- 
  - name: Demo on loop
    hosts: localhost
    connection: local
    vars:
      items_to_loop:
        - {name: bus, price: 10k}
        - {name: car, price: 20k}
        - {name: bike, price: 25k}
        - {name: auto, price: 30K}
    tasks:
      - name: printing vehicals
        ansible.builtin.debug:
          msg: "the vehicle name is {{ item.name }}, price is {{ item.price }}"
        loop: "{{ items_to_loop }}"

  