---
- name: Setup Frontend
  hosts: all
  become: yes # To run commands as root 
  tasks:
    - name: Install Nginx Server
      yum:
        name: nginx
        state: present
    
    - name: Remove the Directory
      file:
        path: /usr/share/nginx/html
        state: absent